# This file is the entry point to configure your own services and load the default configuration.
# If you want to remove a service, deprecate it, or change its class, you can apply the changes here.
#
# If you are *not* using the default services.yaml file in your package, you *must* pass an
# empty array to the $configs argument of the $this->load() method in your Kernel class:
#
#     $this->load([], []);

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Sonata Admin services
    app.admin.news_source:
        class: App\Admin\NewsSourceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Новости', label: 'Источники новостей' }
        arguments:
            - null
            - App\Entity\NewsSource
            - null

    app.admin.news_item:
        class: App\Admin\NewsItemAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Новости', label: 'Новости' }
        arguments:
            - null
            - App\Entity\NewsItem
            - null